[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.16"
fs_permissions = [{ access = "read-write", path = "./"}, { access = "read-write", path = "./records/"}]
# gas_reports = ["Contract_Name"]
ffi = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[fmt]
# see prettier

[fuzz]
runs = 256
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

[invariant]
runs = 256
depth = 15
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true